name: capsicum
description: Client for fedi instances enhanced with mulukhiya-toot-proxy
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yaml: ^3.1.1
  flutter_launcher_icons: ^0.10.0
  shared_preferences: ^2.0.5
  http: ^0.13.5
  logger: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - config/
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png
capsicum:
  instances:
    - name: キュアスタ！
      domain: precure.ml
    - name: デルムリン丼
      domain: mstdn.delmulin.com
    - name: 美食丼
      domain: mstdn.b-shock.org
