package:
  version: 1.0.0
  url: https://github.com/pooza/capsicum
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
cert:
  url: https://curl.haxx.se/ca/cacert.pem
wikipedia:
  url: https://ja.wikipedia.org/
  pllimit: 500
postgres:
  dsn: postgres://postgres@localhost:5432/capsicum
sidekiq:
  redis:
    dsn: redis://localhost:6379/3
  auth:
    user: admin
    password: ''
